import { useEffect, useState } from 'react';
import { Bar, BarChart, CartesianGrid, Cell, Legend, Line, LineChart, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import { getAnalytics } from '../api/analytics';

const money = (value) => new Intl.NumberFormat('ar-EG', { style: 'currency', currency: 'EGP', maximumFractionDigits: 0 }).format(value || 0);
const colors = ['#60a5fa', '#a78bfa', '#f59e0b', '#fb7185', '#34d399', '#f472b6'];
export default function Analytics() {
  const [data, setData] = useState(null); const [filters, setFilters] = useState({ from: '', to: '', search: '' });
  const load = () => getAnalytics(filters).then(setData); useEffect(() => { load(); }, []);
  const exportReport = () => { const blob = new Blob([JSON.stringify(data, null, 2)], { type: 'application/json' }); const url = URL.createObjectURL(blob); const link = document.createElement('a'); link.href = url; link.download = 'analytics-report.json'; link.click(); URL.revokeObjectURL(url); };
  if (!data) return <div className="space-y-4 animate-pulse"><div className="h-8 w-40 rounded bg-white/10"/><div className="h-32 rounded-3xl bg-white/5"/><div className="h-56 rounded-3xl bg-white/5"/></div>;
  const cards = [['الدخل', data.summary.income, 'text-green-400'], ['المصروفات', data.summary.expense, 'text-red-400'], ['التدفق النقدي', data.summary.balance, 'text-blue-400']];
  return <div className="space-y-5"><header><p className="text-blue-400 text-sm">تحليلات تفصيلية</p><h1 className="text-2xl font-bold">التقارير</h1></header><form onSubmit={(e) => { e.preventDefault(); load(); }} className="grid grid-cols-2 gap-2 rounded-2xl bg-white/5 p-3"><input type="date" className="field" value={filters.from} onChange={(e) => setFilters({ ...filters, from: e.target.value })}/><input type="date" className="field" value={filters.to} onChange={(e) => setFilters({ ...filters, to: e.target.value })}/><input className="field col-span-2" placeholder="بحث في المعاملات" value={filters.search} onChange={(e) => setFilters({ ...filters, search: e.target.value })}/><button className="rounded-xl bg-blue-500 py-2 font-bold">تطبيق الفلاتر</button><button type="button" onClick={exportReport} className="rounded-xl border border-white/15 py-2">تصدير التقرير</button></form><section className="grid grid-cols-3 gap-2">{cards.map(([title, value, color]) => <div className="rounded-2xl bg-white/5 p-3" key={title}><p className="text-xs text-gray-400">{title}</p><p className={`mt-1 text-sm font-bold ${color}`}>{money(value)}</p></div>)}</section><Chart title="الدخل مقابل المصروفات شهريًا"><BarChart data={data.monthly}><CartesianGrid stroke="#ffffff12"/><XAxis dataKey="month"/><YAxis/><Tooltip/><Legend/><Bar dataKey="income" fill="#34d399" name="دخل"/><Bar dataKey="expense" fill="#fb7185" name="مصروف"/></BarChart></Chart><Chart title="الاتجاه الشهري"><LineChart data={data.monthly}><CartesianGrid stroke="#ffffff12"/><XAxis dataKey="month"/><YAxis/><Tooltip/><Line type="monotone" dataKey="income" stroke="#34d399"/><Line type="monotone" dataKey="expense" stroke="#fb7185"/></LineChart></Chart><Chart title="توزيع المصروفات حسب الفئة"><PieChart><Pie data={data.categories} dataKey="amount" nameKey="name" outerRadius={80}>{data.categories.map((entry, index) => <Cell key={entry.name} fill={colors[index % colors.length]}/>)}</Pie><Tooltip/></PieChart></Chart><List title="أعلى الفئات" rows={data.categories}/><List title="أعلى الحسابات (التدفق الصافي)" rows={data.accounts}/><section className="rounded-3xl border border-white/10 bg-white/5 p-5"><h2 className="mb-3 font-bold">خريطة الإنفاق الأسبوعية</h2><div className="grid grid-cols-7 gap-1">{data.heatmap.map((cell) => <div key={cell.day} title={money(cell.amount)} className="rounded-lg p-2 text-center text-xs" style={{ background: `rgba(59,130,246,${Math.min(.85, .1 + cell.amount / (Math.max(...data.heatmap.map((entry) => entry.amount), 1)) * .75)})` }}>{['ح','ن','ث','ر','خ','ج','س'][cell.day]}</div>)}</div></section></div>;
}
function Chart({ title, children }) { return <section className="rounded-3xl border border-white/10 bg-white/5 p-4"><h2 className="mb-3 font-bold">{title}</h2><div className="h-60"><ResponsiveContainer width="100%" height="100%">{children}</ResponsiveContainer></div></section>; }
function List({ title, rows }) { return <section className="rounded-3xl border border-white/10 bg-white/5 p-4"><h2 className="mb-3 font-bold">{title}</h2>{rows.length ? rows.map((row) => <div className="flex justify-between border-t border-white/5 py-2 text-sm" key={row.name}><span>{row.name}</span><span>{money(row.amount)}</span></div>) : <p className="text-sm text-gray-400">لا توجد بيانات في الفترة المختارة.</p>}</section>; }
